### ISSUE TITLE
in case embedded db is restored, SMTP auth password isn't restored correctly?

### ISSUE THREAD

**Issue by corselia** [support-project/knowledge#738]
# summary
- when restore embedded db, mail can't be send

# screenshot of error message
![20170524124002](https://cloud.githubusercontent.com/assets/14275619/26390642/67665320-409a-11e7-935e-7f6f663677b0.png)

# resolve
- from error message, I re-entered `SMTP auth password` and pushed save button. so mail can be send

# reason
- as title, I consider

**Comment by koda-masaru** [comment]
Did you restore data only to the `db` folder in the knowledge data directory?
When restoring, please also include `key.txt` in the knowledge data directory.

In Knowledge, the user's login password is stored as an irreversible hash value.(No relation to key.txt)
On the other hand, values like SMTP passwords are encrypted, and can be restored values.

If database data is stolen, in order to prevent you from restoring the password alone, I have a key to unlock the encryption in the Knowledge application server.
BadPaddingException is raised if Key is different.
This is useful when the application server and Database server are separate.

Once saved again, the encrypted value with the key on the server is saved, so you can send mail. (If key.txt does not exist, system generates it.)

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.

**Comment by corselia** [comment]
@koda-masaru 
I see. when needed, I suppose on new issue.
thank you
