### ISSUE TITLE
Custom markdown

### ISSUE THREAD

**Issue by garp5000** [support-project/knowledge#821]
Hello,

I would like to know if is it possible to create custom markdown & emojis, or create custom css? 

Thanks

**Comment by koda-masaru** [comment]
Hi,

## custom markdown

Conversion processing from Markdown to HTML is implemented in the following classes: 

[MarkdownLogic](https://github.com/support-project/knowledge/blob/master/src/main/java/org/support/project/knowledge/logic/MarkdownLogic.java)

And I use the markdj library in 'MarkdownLogic'.
[markdj](https://github.com/support-project/markedj)

You can customize Markdown in MarkdownLogic.
(Because of HTML sanitization, HTML conversion from Markdown is done on the server side)

----------

## emoji

Changing emoji is not easy. If you want to change, would you read [knowledge-common.js](https://github.com/support-project/knowledge/blob/master/src/main/webapp/js/knowledge-common.js)

**Comment by garp5000** [comment]
Thank you, I'll take a look on this. 
For information I've see that's possible to add html code an use the <div> tag with the attribute : style. That's a good thing to enhence the content 😄
