### ISSUE TITLE
Keyboard shortcuts not working in slideshow except Firefox.

### ISSUE THREAD

**Issue by nyoronjp** [support-project/knowledge#860]
スライドショーで矢印キーによる操作がFirefox以外のブラウザでできない。

🆗 Firefox
🆖 IE, Edge, Chrome

OS: Windows 10
Browser version: Latest
Knowledge: v1.10(Stable) and [here](https://support-project.org/open.knowledge/view/18)

----

Knowledgeがサポートしているブラウザとバージョンってどこかに明記してありましたっけ？
IEの件は知ってますがそれ以外について知りたいです。

**Comment by koda-masaru** [comment]
Knowledge is support latest chrome and firefox.
And maybe available latest edge and safari.

Then, "Keyboard shortcuts not working in slideshow except Firefox" is bug.
I will fix it.

Since I can not be test sufficiently, if you find some wrong, please register Issues.

-----

KowledgeはChromeとFirefoxの最新版をサポートしようと思っています。
（テストもその二つのブラウザで実施しています。充分なテストではないですけれど）
たぶんEdgeやSafariでも動くと思います。細かいところは変な動作になるかもしれませんけど。

このため、表題のFireFox以外で動かないというのは不具合だと思います。
後日修正しようと思います。

テストがなかなか十分に実施できないので、もし変な動きを見つけたらIssue登録をお願いします。

**Comment by nyoronjp** [comment]
Thank you. I understand.

OK.  I register Issues if find. :smile:

**Comment by nyoronjp** [comment]
Knowledge v1.11.0 pre2

I confirmed working at Chrome.
Thanks.
