### ISSUE TITLE
Knowledgeとslackとの連携

### ISSUE THREAD

**Issue by tetuya0703** [support-project/knowledge#945]
過去に掲題と同じ内容のissueの内容で議論がされていたように思います
確認する限り、1年前のようでした

現時点のKnowledgeにおいてもslackとの連携はできないのでしょうか
少なくとも小生の環境からはslackとの連携は出来ませんでした

Knowledgeのバージョンはv1.8.1です

よろしくお願い申し上げます

**Comment by koda-masaru** [comment]
I'm not sure to answer because I don't use "Slack".
I think that it is necessary to devise a way to connect Knowledge to Slack. 
Please see this information.
https://qiita.com/tfuruya/items/b16c124cb083e5b6ade6
If you can change the JSON to send, can you connect to Slack?

-----

私はSlackを使っていないので、連携できるかわかりません。
ただ、ネットを検索すると連携するためには、一工夫いるようです。
https://qiita.com/tfuruya/items/b16c124cb083e5b6ade6
送信するJSONの型を変更できるようにすれば、Slackに連携できますか？

※ 最近、海外のかたのアクセスが増えてきて、「できれば英語で書いてほしい」というリクエストが来ています。ですので日本語での問い合わせは以下のサイトに登録願います。
https://service-knowledge.support-project.org/

**Comment by takerushi** [comment]
「記事が作成されたらSlackでメッセージを送る」なら、

「一定間隔（60秒とか）でAPI（`GET /api/knowledges `）にリクエストして、変更があったらSlackでメッセージを送る処理をする」
とかでいいんじゃないでしょうかね。

個人的に、せっかくAPIを提供しているのに他アプリケーションとの連携の実装をやる必要はないと考えます。

**Comment by koda-masaru** [comment]
たしかに、Web APIを使って実現することもありですね 👍 

ただ、Web APIを自前でホストするのは面倒という利用者もいると思いますし、WebHookの通知のJSONの型が固定というのも不親切かなと思いましたので、↓にあるイイネが押されたときのWebhook通知機能を作るついでに変更できるようにしてみました。
https://service-knowledge.support-project.org/open.knowledge/view/28

カスタマイズ方法は、以下のようなテンプレートのJSONを変更していきます。

```
{
    "type": "knowledge",
    "comment_count": "{knowledge.commentCount}",
    "like_count": "{knowledge.likeCount}",
    "became_public": "{knowledge.became_public}",
    "type_id": "{knowledge.typeId}",
    "insert_date": "{knowledge.insertDatetime,format=yyyy/MM/dd HH:mm:ss.SSSZ}",
    "link": "{knowledge.link}",
    "groups": "{knowledge.groups}",
    "insert_user": "{knowledge.insertUserName}",
    "title": "{knowledge.title}",
    "content": "{knowledge.content}",
    "update_date": "{knowledge.updateDatetime,format=yyyy/MM/dd HH:mm:ss.SSSZ}",
    "tags": "{knowledge.tags}",
    "update_user": "{knowledge.updateUserName}",
    "text": "<{knowledge.link}|{knowledge.title}>",
    "public_flag": "{knowledge.publicFlag}",
    "knowledge_id": "{knowledge.knowledgeId}",
    "status": "{knowledge.status}"
}
```

JSONの編集なので、多少の知識は必要ですが、これくらいなら簡単に変更できるかなと思っています。

**Comment by koda-masaru** [comment]
あと、今、Slackを使ってみて、WebHook連携を試してみたのですが、何もしなくても普通に連携できました。（最新版にて確認 / Webhookのカスタマイズ機能が入っているもの@developブランチ）

**Comment by koda-masaru** [comment]
This issue is available on v1.12.0 pre1.
