### ISSUE TITLE
How to disable mail notification for suspended users

### ISSUE THREAD

**Issue by lufia** [support-project/knowledge#984]
We use Knowledge in this rules:

* Log in to Knowledge with LDAP
* Retired members are suspended in LDAP
* Users of Knowledge is not deleted

The retired user is not able to authenticate but it still exists.
Therefore if it is set email notification, administrators of Knowledge is not able to stop notification.

**Comment by koda-masaru** [comment]
As you pointed out, 'Knowledge' does not have an administrator function to stop e-mail notification to retired members.
This problem is known, but I have not been able to respond yet. same issue #330 
And I am updating database data directly and stopping email notification.

Can you operate the database directly?
If you can do that, I will tell you how to stop e-mail notifications.

**Comment by lufia** [comment]
@koda-masaru 
Thank you for your response. I can operate 'Knowledge' database.
I seen that. Like this?

```sql
update notify_configs set notify_mail = 0 where user_id = (user_id);
```

**Comment by koda-masaru** [comment]
You are right.
The system does not send e-mails to users who set notify_mail in the notify_configs table to 0.

**Comment by lufia** [comment]
Thank you. I'm looking forward to solving #330.
